'use client';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
const sb=createClient('https://ssukleiuwjqmfruagmwk.supabase.co','sb_publishable_pZrsR-vEyCNYXZdk-qSVbQ_EDD0KwyJ');
const tabs=['Tableau de bord','Clients','Devis','Projets','Emails','SAV','Prospection'];
const eur=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format((n||0)/100);
const d=v=>v?new Date(v).toLocaleDateString('fr-FR'):'—';
const subject='Partenariat Cuisine Pour Tous';
const partnershipText=`Bonjour,\n\nCuisine Pour Tous à Chambéry développe son réseau de partenaires et apporteurs d’affaires autour de la cuisine équipée italienne au meilleur rapport qualité/prix.\n\nNous accompagnons vos clients de l’étude à la réalisation, avec conception et implantation 3D. Un partenariat peut également prévoir une rémunération pour les affaires apportées.\n\nJe serais ravi d’échanger avec vous afin de vous présenter simplement notre fonctionnement.\n\nBien cordialement,\nCuisine Pour Tous\ncontact@cuisinepourtouschambery.fr`;
export default function Page(){
 const [session,setSession]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[tab,setTab]=useState('Tableau de bord'),[prospects,setProspects]=useState([]),[clients,setClients]=useState([]),[quotes,setQuotes]=useState([]),[projects,setProjects]=useState([]),[emails,setEmails]=useState([]),[sav,setSav]=useState([]),[tasks,setTasks]=useState([]),[selectedMail,setSelectedMail]=useState(null),[q,setQ]=useState(''),[status,setStatus]=useState('Tous'),[notice,setNotice]=useState(''),[sending,setSending]=useState('');
 useEffect(()=>{sb.auth.getSession().then(({data})=>setSession(data.session));const {data:l}=sb.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load()},[session]);
 async function load(){const names=['prospects','clients','quotes','projects','inbound_emails','sav_tickets','project_tasks'];const r=await Promise.all(names.map(n=>sb.from(n).select('*')));setProspects(r[0].data||[]);setClients(r[1].data||[]);setQuotes(r[2].data||[]);setProjects(r[3].data||[]);setEmails((r[4].data||[]).filter(x=>!x.deleted_at).sort((a,b)=>new Date(b.received_at)-new Date(a.received_at)));setSav(r[5].data||[]);setTasks(r[6].data||[])}
 async function login(e){e.preventDefault();setError('');const {error}=await sb.auth.signInWithPassword({email,password});if(error)setError(error.message)} async function logout(){await sb.auth.signOut()}
 async function patch(table,id,data,setter){const {error}=await sb.from(table).update(data).eq('id',id);if(error){setNotice('Erreur : '+error.message);return false}setter(x=>x.map(v=>v.id===id?{...v,...data}:v));return true}
 async function sendMail(to,sub,text,key='mail'){setSending(key);setNotice('');try{const r=await fetch('/api/send-email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({to,subject:sub,text})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Envoi impossible');setNotice(`Email envoyé à ${to}`);return true}catch(e){setNotice('Erreur : '+e.message);return false}finally{setSending('')}}
 const overdue=quotes.filter(x=>x.decision_date&&new Date(x.decision_date)<new Date()&&!['accepted','won','refused','lost','accepté','refusé'].includes((x.status||'').toLowerCase()));
 async function remind(x){if(!x.client_email)return setNotice('Aucun email client sur ce devis.');const ok=await sendMail(x.client_email,`Votre projet cuisine${x.quote_number?' - '+x.quote_number:''}`,`Bonjour ${x.client_first_name||x.client_name||''},\n\nJe me permets de revenir vers vous concernant votre projet de cuisine et le devis que nous vous avons remis. Avez-vous pu avancer dans votre réflexion ?\n\nJe reste disponible pour toute modification ou question.\n\nBien cordialement,\nCuisine Pour Tous\ncontact@cuisinepourtouschambery.fr`,x.id);if(ok)await patch('quotes',x.id,{email_sent_at:new Date().toISOString()},setQuotes)}
 async function openMail(m){setSelectedMail(m);if(!m.read_at)await patch('inbound_emails',m.id,{read_at:new Date().toISOString()},setEmails)}
 async function deleteMail(m){if(await patch('inbound_emails',m.id,{deleted_at:new Date().toISOString()},setEmails)){setEmails(x=>x.filter(v=>v.id!==m.id));setSelectedMail(null)}}
 if(session===null)return <main className="login"><form onSubmit={login} className="loginCard"><div className="brand">C<span>F</span></div><h1>CuisineFlow</h1><p>Chaque cuisine suivie, de la signature au SAV.</p><label>Adresse e-mail professionnelle</label><input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/><label>Mot de passe</label><input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/><button>Se connecter</button>{error&&<div className="error">{error}</div>}</form></main>;
 return <div className="shell"><aside><div className="sideBrand"><b>CuisineFlow</b><small>Cuisine Pour Tous</small></div>{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}<div className="grow"/><button onClick={logout}>Déconnexion</button></aside><main className="content"><header><div><h1>{tab}</h1><p>Commandes, livraisons, poses et clients réunis dans un seul espace.</p></div><button className="refresh" onClick={load}>Actualiser</button></header>{notice&&<section className="panel notice">{notice}</section>}
 {tab==='Tableau de bord'&&<><section className="stats"><Stat n={clients.length} l="Clients"/><Stat n={quotes.length} l="Devis"/><Stat n={projects.length} l="Projets"/><Stat n={sav.filter(x=>(x.status||'').toLowerCase()!=='résolu').length} l="SAV ouverts"/><Stat n={overdue.length} l="Devis à relancer" alert={overdue.length>0}/></section><section className="panel"><h2>À faire maintenant</h2>{overdue.length?overdue.slice(0,8).map(x=><Row key={x.id} title={`${x.quote_number||'Devis'} · ${x.client_name||'Client'}`} sub={`Décision prévue le ${d(x.decision_date)} · ${eur(x.total_cents)}`} action={<button onClick={()=>remind(x)} disabled={sending===x.id}>Relancer</button>}/>):<p>Aucun devis en retard.</p>}<h2>Prochaines étapes projets</h2>{projects.filter(x=>x.next_step).slice(0,6).map(x=><Row key={x.id} title={x.client_name||x.reference} sub={`${x.next_step} · échéance ${d(x.due_date)}`}/>)}</section></>}
 {tab==='Clients'&&<Data title={`${clients.length} clients`} headers={['Client','Coordonnées','Adresse','Créé le']} rows={clients.map(x=>[<b>{[x.first_name,x.last_name].filter(Boolean).join(' ')||'Client'}</b>,<span>{x.email||'—'}<br/>{x.phone||''}</span>,<span>{x.address||''}<br/>{x.postal_code||''} {x.city||''}</span>,d(x.created_at)])}/>} 
 {tab==='Devis'&&<><section className="panel"><h2>Devis et dates de décision</h2><p>Les devis arrivés à leur date de décision peuvent être relancés directement depuis CuisineFlow.</p></section><Data headers={['N°','Client','Montant','Statut','Date décision','Documents','Action']} rows={quotes.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).map(x=>[x.quote_number||'—',<span><b>{x.client_name||'—'}</b><br/>{x.client_email||''}</span>,eur(x.total_cents),x.status||'—',<span className={x.decision_date&&new Date(x.decision_date)<new Date()?'late':''}>{d(x.decision_date)}</span>,<span>{x.source_pdf_path?'Devis PDF ✓':'—'}<br/>{x.signed_order_path?'Commande signée ✓':''}</span>,<button onClick={()=>remind(x)} disabled={!x.client_email||sending===x.id}>Relancer</button>])}/></>}
 {tab==='Projets'&&<><section className="panel"><h2>Commandes · livraisons · poses</h2></section><Data headers={['Référence','Client','Ville','Montant','Statut','Avancement','Prochaine étape','Échéance']} rows={projects.map(x=>[x.reference||'—',x.client_name||'—',x.city||'—',eur(x.amount_cents),x.status||'—',<span>{x.progress||0}%<progress max="100" value={x.progress||0}/></span>,x.next_step||'—',d(x.due_date)])}/><section className="panel"><h2>Tâches projets</h2>{tasks.length?tasks.map(x=><Row key={x.id} title={x.title} sub={`${x.completed?'Terminée':'À faire'} · ${d(x.due_date)}`}/>):<p>Aucune tâche.</p>}</section></>}
 {tab==='Emails'&&<section className="mailbox"><div className="mailList"><div className="mailHead"><b>Boîte de réception</b><button onClick={load}>Actualiser</button></div>{emails.map(m=><button key={m.id} className={'mailItem '+(selectedMail?.id===m.id?'selected ':'')+(!m.read_at?'unread':'')} onClick={()=>openMail(m)}><b>{m.from_address||'Expéditeur'}</b><span>{m.subject||'(sans objet)'}</span><small>{d(m.received_at)}</small></button>)}</div><div className="mailBody">{selectedMail?<><h2>{selectedMail.subject||'(sans objet)'}</h2><p><b>De :</b> {selectedMail.from_address}</p><div className="mailActions"><button onClick={()=>sendMail(selectedMail.from_address,'Re: '+(selectedMail.subject||''),'Bonjour,\n\n\n\nBien cordialement,\nCuisine Pour Tous',selectedMail.id)}>Répondre</button><button className="danger" onClick={()=>deleteMail(selectedMail)}>Supprimer</button></div><article>{selectedMail.text_body||'Email HTML reçu. Le contenu texte n’est pas disponible.'}</article></>:<div className="emptyMail">Cliquez sur un email pour l’ouvrir ici.</div>}</div></section>}
 {tab==='SAV'&&<Data title={`${sav.length} dossiers SAV`} headers={['Ticket','Client','Sujet','Priorité','Statut','Rendez-vous','Fournisseur']} rows={sav.map(x=>[x.ticket_number||'—',<span>{x.client_name||'—'}<br/>{x.client_phone||''}</span>,<span><b>{x.title}</b><br/>{x.description||''}</span>,x.priority||'—',x.status||'—',d(x.scheduled_for),<span>{x.supplier_reference||'—'}<br/>{x.supplier_email_sent_at?'Email envoyé ✓':''}</span>])}/>} 
 {tab==='Prospection'&&<Prospection prospects={prospects} q={q} setQ={setQ} status={status} setStatus={setStatus} update={(id,data)=>patch('prospects',id,data,setProspects)} send={async p=>{if(!p.email)return;const ok=await sendMail(p.email,subject,partnershipText,p.id);if(ok)await patch('prospects',p.id,{status:'Contacté',last_contact_at:new Date().toISOString()},setProspects)}} sending={sending}/>} 
 </main></div>}
function Stat({n,l,alert}){return <div className={'stat '+(alert?'warn':'')}><b>{n}</b><span>{l}</span></div>}
function Row({title,sub,action}){return <div className="row"><div><b>{title}</b><small>{sub}</small></div>{action}</div>}
function Data({title,headers,rows}){return <section className="panel tableWrap">{title&&<h2>{title}</h2>}<table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>):<tr><td colSpan={headers.length}>Aucun élément.</td></tr>}</tbody></table></section>}
function Prospection({prospects,q,setQ,status,setStatus,update,send,sending}){const statuses=['Tous',...new Set(prospects.map(p=>p.status).filter(Boolean))];const filtered=prospects.filter(p=>(status==='Tous'||p.status===status)&&(`${p.company_name||''} ${p.contact_name||''} ${p.city||''} ${p.email||''}`).toLowerCase().includes(q.toLowerCase()));return <><section className="toolbar"><input placeholder="Rechercher société, ville, contact…" value={q} onChange={e=>setQ(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select><b>{filtered.length} prospects professionnels</b></section><Data headers={['Société','Contact','Ville','Priorité','Statut','Prochaine relance','Coordonnées','Action']} rows={filtered.map(p=>[<span><b>{p.company_name}</b><br/>{p.prospect_type||''}</span>,p.contact_name||'—',p.city||'—',p.priority||'—',<select value={p.status||''} onChange={e=>update(p.id,{status:e.target.value})}><option>À contacter</option><option>Contacté</option><option>À relancer</option><option>Intéressé</option><option>Partenaire</option><option>Non intéressé</option></select>,d(p.next_follow_up_at),<span>{p.email||'Pas d’email'}<br/>{p.phone||''}</span>,p.email?<button onClick={()=>send(p)} disabled={sending===p.id}>{sending===p.id?'Envoi…':'Envoyer l’email'}</button>:'À qualifier'])}/></>}
