'use client';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
const sb=createClient('https://ssukleiuwjqmfruagmwk.supabase.co','sb_publishable_pZrsR-vEyCNYXZdk-qSVbQ_EDD0KwyJ');
const tabs=['Tableau de bord','Prospection','Clients','Devis','Projets','Emails','SAV'];
const subject='Partenariat Cuisine Pour Tous';
const partnershipText=`Bonjour,\n\nCuisine Pour Tous à Chambéry développe son réseau de partenaires et apporteurs d’affaires autour de la cuisine équipée italienne au meilleur rapport qualité/prix.\n\nNous accompagnons vos clients de l’étude à la réalisation, avec conception et implantation 3D. Un partenariat peut également prévoir une rémunération pour les affaires apportées.\n\nJe serais ravi d’échanger avec vous afin de vous présenter simplement notre fonctionnement.\n\nBien cordialement,\nCuisine Pour Tous\ncontact@cuisinepourtouschambery.fr`;
export default function Page(){
 const [session,setSession]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[tab,setTab]=useState('Tableau de bord'),[prospects,setProspects]=useState([]),[clients,setClients]=useState([]),[quotes,setQuotes]=useState([]),[projects,setProjects]=useState([]),[q,setQ]=useState(''),[status,setStatus]=useState('Tous'),[notice,setNotice]=useState(''),[sending,setSending]=useState('');
 useEffect(()=>{sb.auth.getSession().then(({data})=>setSession(data.session));const {data:l}=sb.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load()},[session]);
 async function load(){const [p,c,d,j]=await Promise.all([sb.from('prospects').select('*').order('created_at',{ascending:false}),sb.from('clients').select('*'),sb.from('quotes').select('*'),sb.from('projects').select('*')]);setProspects(p.data||[]);setClients(c.data||[]);setQuotes(d.data||[]);setProjects(j.data||[])}
 async function login(e){e.preventDefault();setError('');const {error}=await sb.auth.signInWithPassword({email,password});if(error)setError(error.message)}
 async function logout(){await sb.auth.signOut()}
 async function updateProspect(id,patch){const {error}=await sb.from('prospects').update(patch).eq('id',id);if(!error)setProspects(x=>x.map(p=>p.id===id?{...p,...patch}:p))}
 async function sendMail(to,sub,text,key='test'){setSending(key);setNotice('');try{const r=await fetch('/api/send-email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({to,subject:sub,text})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Envoi impossible');setNotice(`Email envoyé à ${to}`);return true}catch(e){setNotice(`Erreur : ${e.message}`);return false}finally{setSending('')}}
 async function testSmtp(){if(!session?.user?.email){setNotice('Adresse de test introuvable.');return}await sendMail(session.user.email,'Test CuisineFlow - messagerie connectée','Bonjour,\n\nCeci est un email de test envoyé automatiquement depuis CuisineFlow.\n\nSi vous recevez ce message, la connexion SMTP fonctionne.\n\nCuisine Pour Tous','test')}
 async function sendProspect(p){if(!p.email)return;const ok=await sendMail(p.email,subject,partnershipText,p.id);if(ok)await updateProspect(p.id,{status:'Contacté'})}
 const filtered=useMemo(()=>prospects.filter(p=>(status==='Tous'||p.status===status)&&(`${p.company_name||''} ${p.contact_name||''} ${p.city||''} ${p.email||''}`).toLowerCase().includes(q.toLowerCase())),[prospects,q,status]);
 if(session===null)return <main className="login"><form onSubmit={login} className="loginCard"><div className="brand">C<span>F</span></div><h1>CuisineFlow</h1><p>Chaque cuisine suivie, de la signature au SAV.</p><label>Adresse e-mail professionnelle</label><input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/><label>Mot de passe</label><input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/><button>Se connecter</button>{error&&<div className="error">{error}</div>}</form></main>;
 const overdue=quotes.filter(x=>x.decision_date&&new Date(x.decision_date)<new Date()&&!['accepted','won','refused','lost'].includes((x.status||'').toLowerCase())).length;
 return <div className="shell"><aside><div className="sideBrand"><b>CuisineFlow</b><small>Cuisine Pour Tous</small></div>{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}<div className="grow"/><button onClick={logout}>Déconnexion</button></aside><main className="content"><header><div><h1>{tab}</h1><p>CRM commercial · Cuisine Pour Tous</p></div><button className="refresh" onClick={load}>Actualiser</button></header>{notice&&<section className="panel"><b>{notice}</b></section>}
 {tab==='Tableau de bord'&&<><section className="stats"><Stat n={prospects.length} l="Prospects professionnels"/><Stat n={clients.length} l="Clients"/><Stat n={quotes.length} l="Devis"/><Stat n={projects.length} l="Projets"/><Stat n={overdue} l="Devis à relancer" alert={overdue>0}/></section><section className="panel"><h2>Messagerie professionnelle</h2><p>Teste d’abord la connexion SMTP. L’email de test sera envoyé à ton adresse de connexion CuisineFlow.</p><button onClick={testSmtp} disabled={sending==='test'}>{sending==='test'?'Envoi en cours…':'Tester l’envoi email'}</button></section></>}
 {tab==='Prospection'&&<Prospection prospects={filtered} all={prospects} q={q} setQ={setQ} status={status} setStatus={setStatus} update={updateProspect} send={sendProspect} sending={sending}/>} 
 {tab!=='Tableau de bord'&&tab!=='Prospection'&&<section className="panel"><h2>{tab}</h2><p>Module connecté à la base CuisineFlow.</p><div className="empty">{tab==='Clients'?clients.length:tab==='Devis'?quotes.length:tab==='Projets'?projects.length:'—'} éléments</div></section>}
 </main></div>}
function Stat({n,l,alert}){return <div className={'stat '+(alert?'warn':'')}><b>{n}</b><span>{l}</span></div>}
function Prospection({prospects,all,q,setQ,status,setStatus,update,send,sending}){const statuses=['Tous',...new Set(all.map(p=>p.status).filter(Boolean))];return <><section className="toolbar"><input placeholder="Rechercher société, ville, contact…" value={q} onChange={e=>setQ(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select><b>{prospects.length} prospects</b></section><section className="panel tableWrap"><table><thead><tr><th>Société</th><th>Contact</th><th>Ville</th><th>Priorité</th><th>Statut</th><th>Coordonnées</th><th>Action</th></tr></thead><tbody>{prospects.map(p=><tr key={p.id}><td><strong>{p.company_name}</strong><small>{p.prospect_type}</small></td><td>{p.contact_name||'—'}</td><td>{p.city||'—'}</td><td><span className={'pill '+(p.priority||'').toLowerCase()}>{p.priority||'—'}</span></td><td><select value={p.status||''} onChange={e=>update(p.id,{status:e.target.value})}><option value="À contacter">À contacter</option><option value="Contacté">Contacté</option><option value="À relancer">À relancer</option><option value="Intéressé">Intéressé</option><option value="Partenaire">Partenaire</option><option value="Non intéressé">Non intéressé</option></select></td><td><small>{p.email||'Pas d’email'}<br/>{p.phone||''}</small></td><td>{p.email?<button className="mail" onClick={()=>send(p)} disabled={sending===p.id}>{sending===p.id?'Envoi…':'Envoyer l’email'}</button>:<span className="muted">À qualifier</span>}</td></tr>)}</tbody></table></section></>}
